// app/affiliate-disclosure/page.js
export const metadata = {
  title: 'Affiliate Disclosure — Alpkoll',
  description: 'How Alpkoll earns revenue through affiliate partnerships with Booking.com and Skyscanner.',
};

export default function AffiliateDisclosurePage() {
  return (
    <main style={{
      minHeight: '100vh',
      background: '#121110',
      color: '#f0ece4',
      padding: '120px clamp(24px, 4vw, 64px) 80px',
    }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>
        {/* Header */}
        <p style={{
          fontFamily: "'Barlow', sans-serif",
          fontSize: 12,
          fontWeight: 600,
          color: '#D4A574',
          letterSpacing: '0.15em',
          textTransform: 'uppercase',
          marginBottom: 12,
        }}>
          LEGAL
        </p>
        <h1 style={{
          fontFamily: "'Bebas Neue', sans-serif",
          fontSize: 'clamp(36px, 5vw, 56px)',
          color: '#f0ece4',
          letterSpacing: '0.03em',
          lineHeight: 1.1,
          marginBottom: 12,
        }}>
          Affiliate Disclosure
        </h1>
        <p style={{
          fontFamily: "'Barlow', sans-serif",
          fontSize: 14,
          color: 'rgba(255,255,255,0.3)',
          marginBottom: 48,
        }}>
          Last updated: March 2026
        </p>

        {/* Content */}
        <div style={{
          fontFamily: "'Barlow', sans-serif",
          fontSize: 15,
          lineHeight: 1.8,
          color: 'rgba(255,255,255,0.65)',
        }}>
          <Section title="How Alpkoll earns revenue">
            <p>
              Alpkoll is a free tool. We earn revenue through affiliate partnerships — when you 
              click a link to a third-party service and make a booking, we may receive a small 
              commission. This is how we keep the site running without charging you anything.
            </p>
          </Section>

          <Section title="Our affiliate partners">
            <p>
              We currently link to the following services:
            </p>
            <ul style={{ marginTop: 8, paddingLeft: 20 }}>
              <li>
                <strong style={{ color: '#f0ece4' }}>Booking.com</strong> — hotel and accommodation bookings
              </li>
              <li>
                <strong style={{ color: '#f0ece4' }}>Skyscanner</strong> — flight search and comparison
              </li>
            </ul>
            <p style={{ marginTop: 12 }}>
              When you click these links, you are taken to the partner&apos;s website. Any booking 
              you make is between you and that service — Alpkoll is not a party to the transaction.
            </p>
          </Section>

          <Section title="Does this affect our recommendations?">
            <p>
              <strong style={{ color: '#f0ece4' }}>No.</strong> Resort rankings and scores on Alpkoll are 
              generated by a weighted formula based on structured data — snow reliability, terrain, 
              price, accessibility, and other measurable factors. No resort is ranked higher because 
              of an affiliate relationship.
            </p>
            <p style={{ marginTop: 12 }}>
              We believe transparency builds trust. If you ever have questions about how our 
              scoring works, check the{' '}
              <a href="/about" style={{ color: '#D4A574', textDecoration: 'none' }}>
                About page
              </a>{' '}
              or email us.
            </p>
          </Section>

          <Section title="Does it cost you more?">
            <p>
              No. The price you see on Booking.com or Skyscanner is the same whether you arrive 
              through Alpkoll or go directly. Affiliate commissions are paid by the partner, not by you.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions? Reach us at{' '}
              <a href="mailto:hello@alpkoll.com" style={{ color: '#D4A574', textDecoration: 'none' }}>
                hello@alpkoll.com
              </a>.
            </p>
          </Section>
        </div>
      </div>
    </main>
  );
}

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 40 }}>
      <h2 style={{
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 22,
        color: '#f0ece4',
        letterSpacing: '0.04em',
        marginBottom: 12,
      }}>
        {title}
      </h2>
      {children}
    </div>
  );
}